import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        {/* Page 컴포넌트를 전달 받아서 레이아웃 안쪽으로 렌더링해줌 */}
      </body>
    </html>
  )
}

// 이 RootLayout 역할을 하는 이 파일은 절대 없으면 안 되는 파일임.
// HTML의 기초 틀을 유지하게 해줌.
